### ISSUE TITLE
css布局错误

### ISSUE THREAD

**Issue by baicuhaha** [springalskey/picker#2]
大神 在picker弹出的时候！我自己css布局就有问题了！这是为什么？
![2017-03-22 9 34 30](https://cloud.githubusercontent.com/assets/20334376/24178240/e3bebe9c-0ee2-11e7-90bb-d0d64d9249bb.png)

**Comment by springalskey** [comment]
不好意思，才看到你的问题，现在你的问题解决了吗？

**Comment by springalskey** [comment]
我估计是因为在弹出框出现的时候，我设置了body的样式造成的，你可以看下你代码，当初我为什么要设置这样的css呢，是因为这样在手机上触屏的时候，因为穿透而造成的体验不友好。如果你因此受到影响了，你可以写css去覆盖掉。不过我马上会更新一版，把这个样式去掉。顺便再加上点击背景也调用cancel方法移除picker。

**Comment by baicuhaha** [comment]
哦谢了，问题已解决了！

**Comment by springalskey** [comment]
不客气的。
