### ISSUE TITLE
itemHeight建议改成自定义属性

### ISSUE THREAD

**Issue by ilwk** [springalskey/picker#3]
因为在Retina屏幕下px显示太小，而且各种屏幕显示效果不统一，所以我改了ui-picker-item的高度，然后我发现滑动的时候选择会错位，建议将Picker.js中itemHeight改为自动计算。。。

**Comment by springalskey** [comment]
36px不够吗？你的header里是不是没有加<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">，所以导致px太小？

**Comment by springalskey** [comment]
36px不够吗？你的header里是不是没有加‘<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">，’所以导致px太小？

**Comment by springalskey** [comment]
36px可以了的。或许你可以添加meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width" 试试

**Comment by ilwk** [comment]
因为我使用了阿里的高清适配方案，用rem做单位的。。。所以在高清屏下px会很模糊

**Comment by springalskey** [comment]
1即便是rem单位的话，也需要设置meta。
2也不是需要把所有的东西都用rem，通常padding，margin等较小数值、字体大小，小图片等都用固定px
总之，对于没有必要使用rem的，可不使用rem。
我举个例子，input框，height，业内不统一规定，设计师都会设置为44px；而这时候你用rem来做这个height，在小屏幕上，input的height就会很小，这时候，设计师就要找技术pk了。然后再讨论下我这个设置的36px，是一样的意思。你可以思考思考一下。

**Comment by hb-bobo** [comment]
你用了阿里的高清适配方案 还来找这个？ 我觉得
