### ISSUE TITLE
选择时报错

### ISSUE THREAD

**Issue by Notdefind** [springalskey/picker#5]
![image](https://user-images.githubusercontent.com/17826565/32097822-66acdb7e-bad0-11e7-87da-c50bb2d0fb6f.png)

**Comment by springalskey** [comment]
哦，早之前的了，react版本低导致的。我抽空升级修复下，谢谢。

**Comment by springalskey** [comment]
我之前写的时候react版本还比较低，现在react升级了，我没有同步更新这个代码，所以新版本的react里会有点儿问题。

**Comment by springalskey** [comment]
今天刚升级到react16.0版本，现在运行无报错了。
